from .getMe import getMe
from .sendMessage import sendMessage
from .approveChatJoinRequest import approveChatJoinRequest
from .declineChatJoinRequest import declineChatJoinRequest
from .deleteMessage import deleteMessage
from .sendPhoto import sendPhoto
from .logOut import logOut
from .sendVideo import sendVideo
from .close import close
from .forwardMessage import forwardMessage
from .sendDocument import sendDocument